# Generated by Django 2.0.6 on 2018-06-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Pad',
        ),
    ]
