# Generated by Django 2.0.6 on 2018-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0002_auto_20180620_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='entry',
            field=models.CharField(max_length=1024),
        ),
    ]
