# Generated by Django 2.0.6 on 2018-06-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0003_auto_20180620_0834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pad',
            new_name='Entry',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='checked',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry',
            new_name='body',
        ),
    ]
