# Generated by Django 2.0.6 on 2018-06-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0004_auto_20180620_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.TextField(max_length=1024),
        ),
    ]
